plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.ksp)
    alias(libs.plugins.hilt)
    alias(libs.plugins.room)
    alias(libs.plugins.kover)
    alias(libs.plugins.kotlin.serialization)
}

android {
    namespace = "shibbir.me.alquranquotes"
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId = "shibbir.me.alquranquotes"
        minSdk = 24
        targetSdk = 37
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        debug {
            // JaCoCo instruments every app class, which slows the app down, so it is only on when
            // asked for: ./gradlew createDebugCoverageReport -PdeviceTestCoverage (CI passes it).
            enableAndroidTestCoverage = providers.gradleProperty("deviceTestCoverage").isPresent
        }
        release {
            optimization {
                enable = true
            }
        }
    }
    sourceSets {
        named("test") {
            // Lets unit tests read the bundled ayahs.json from the classpath.
            resources.directories.add("src/main/assets")
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
    buildFeatures {
        compose = true
    }
}

room {
    schemaDirectory("$projectDir/schemas")
}

// QuranDatabaseSchemaHistoryTest reads app/schemas from disk. Room's copyRoomSchemas task writes
// the schema of the compiled entities there, so it runs first, or a changed schema would reach
// the test one build late.
tasks.withType<Test>().configureEach {
    dependsOn("copyRoomSchemas")
    val roomSchemaDirectory = layout.projectDirectory.dir("schemas")
    inputs.dir(roomSchemaDirectory).withPathSensitivity(PathSensitivity.RELATIVE)
    systemProperty("roomSchemaDirectory", roomSchemaDirectory.asFile.absolutePath)
}

kover {
    reports {
        filters {
            excludes {
                // Generated by Hilt, Dagger, Room, and the Compose compiler.
                classes(
                    "*Hilt_*",
                    "*_*Factory",
                    "*_*Factory\$*",
                    "*_Impl",
                    "*_Impl\$*",
                    "*_HiltModules*",
                    "*_MembersInjector",
                    "*_GeneratedInjector",
                    "hilt_aggregated_deps.*",
                    "dagger.hilt.internal.*",
                    "*ComposableSingletons*",
                    "*\$\$serializer",
                )
                // Needs the Android framework; instrumented tests in src/androidTest cover it.
                annotatedBy(
                    "androidx.compose.runtime.Composable",
                    "dagger.Module",
                )
                classes(
                    "shibbir.me.alquranquotes.AlQuranQuotesApp",
                    "shibbir.me.alquranquotes.MainActivity",
                    "shibbir.me.alquranquotes.data.local.QuranDatabase",
                    "shibbir.me.alquranquotes.core.time.SystemDayChangeSource",
                    "shibbir.me.alquranquotes.core.time.SystemDayChangeSource\$*",
                    "shibbir.me.alquranquotes.data.seed.AssetAyahSeedSource",
                    "shibbir.me.alquranquotes.data.seed.AssetAyahSeedSource\$*",
                )
                packages("shibbir.me.alquranquotes.ui.theme")
            }
        }
        verify {
            rule("Every class that can run on the JVM is fully covered by unit tests") {
                bound {
                    minValue = 100
                    coverageUnits = kotlinx.kover.gradle.plugin.dsl.CoverageUnit.LINE
                }
                bound {
                    minValue = 100
                    coverageUnits = kotlinx.kover.gradle.plugin.dsl.CoverageUnit.BRANCH
                }
            }
        }
    }
}

dependencies {
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.compose.foundation)
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.compose.material.icons.core)
    implementation(libs.androidx.navigation.compose)
    implementation(libs.kotlinx.serialization.core)
    implementation(libs.androidx.compose.runtime)
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.text)
    implementation(libs.androidx.compose.ui.unit)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.androidx.lifecycle.viewmodel)
    implementation(libs.androidx.lifecycle.viewmodel.savedstate)
    implementation(libs.androidx.lifecycle.runtime.compose)
    implementation(libs.kotlinx.coroutines.android)
    implementation(libs.hilt.android)
    ksp(libs.hilt.compiler)
    implementation(libs.androidx.hilt.lifecycle.viewmodel.compose)
    implementation(libs.androidx.room.runtime)
    ksp(libs.androidx.room.compiler)
    testImplementation(libs.junit)
    testImplementation(libs.kotlinx.coroutines.test)
    testImplementation(libs.org.json)
    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.junit)
    androidTestImplementation(libs.androidx.room.testing)
    androidTestImplementation(libs.kotlinx.coroutines.test)
    androidTestImplementation(libs.androidx.compose.ui.test.junit4)
    androidTestImplementation(libs.androidx.test.runner)
    androidTestImplementation(libs.androidx.junit)
    debugImplementation(libs.androidx.compose.ui.test.manifest)
    debugImplementation(libs.androidx.compose.ui.tooling)
}
